#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_func = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_bool = 5,
  anon_sym_number = 6,
  anon_sym_string = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_return = 10,
  anon_sym_EQ = 11,
  anon_sym_DASH = 12,
  anon_sym_BANG = 13,
  anon_sym_STAR = 14,
  anon_sym_SLASH = 15,
  anon_sym_PLUS = 16,
  anon_sym_EQ_EQ = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_GT = 19,
  anon_sym_LT = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_BANG_EQ = 22,
  sym_identifier = 23,
  sym_number = 24,
  sym_string = 25,
  sym_program = 26,
  sym__definition = 27,
  sym_function_definition = 28,
  sym_parameter_list = 29,
  sym__type = 30,
  sym_primitive_type = 31,
  sym_block = 32,
  sym_return_statement = 33,
  sym__expression = 34,
  sym_variable_declaration = 35,
  sym_variable_definition = 36,
  sym_unary_expression = 37,
  sym_binary_expression = 38,
  aux_sym_program_repeat1 = 39,
  aux_sym_parameter_list_repeat1 = 40,
  aux_sym_block_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_bool] = "bool",
  [anon_sym_number] = "number",
  [anon_sym_string] = "string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_EQ] = "=",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_BANG_EQ] = "!=",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_program] = "program",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_block] = "block",
  [sym_return_statement] = "return_statement",
  [sym__expression] = "_expression",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_definition] = "variable_definition",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_program] = sym_program,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_block] = sym_block,
  [sym_return_statement] = sym_return_statement,
  [sym__expression] = sym__expression,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_definition] = sym_variable_definition,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_code = 1,
  field_left = 2,
  field_name = 3,
  field_operator = 4,
  field_parameters = 5,
  field_right = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_code] = "code",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 3},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_name, 1},
    {field_type, 0},
  [4] =
    {field_name, 0},
    {field_value, 2},
  [6] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [9] =
    {field_value, 2},
  [10] =
    {field_code, 3},
    {field_name, 1},
    {field_parameters, 2},
  [13] =
    {field_code, 4},
    {field_name, 1},
    {field_parameters, 2},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 2,
  [9] = 4,
  [10] = 3,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 16,
  [20] = 12,
  [21] = 17,
  [22] = 15,
  [23] = 23,
  [24] = 18,
  [25] = 13,
  [26] = 7,
  [27] = 11,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 34,
  [39] = 39,
  [40] = 37,
  [41] = 32,
  [42] = 31,
  [43] = 33,
  [44] = 39,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 62,
  [67] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '+') ADVANCE(37);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(33);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '<') ADVANCE(41);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == 'b') ADVANCE(56);
      if (lookahead == 'f') ADVANCE(62);
      if (lookahead == 'n') ADVANCE(63);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '+') ADVANCE(37);
      if (lookahead == '-') ADVANCE(33);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '<') ADVANCE(41);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == 'b') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(63);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == 'b') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 's') ADVANCE(15);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'g') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(4);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(17)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_func);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_number);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_string);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_return);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(19);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(61);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(28);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(53);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(24);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(44);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(45);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(48);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(31);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(55);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(49);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(54);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(57);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(64);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(51);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(59);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 17},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 17},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 17},
  [67] = {.lex_state = 17},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(64),
    [sym__definition] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym_primitive_type] = STATE(65),
    [sym_return_statement] = STATE(14),
    [sym__expression] = STATE(14),
    [sym_variable_declaration] = STATE(4),
    [sym_variable_definition] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_binary_expression] = STATE(14),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_func] = ACTIONS(5),
    [anon_sym_bool] = ACTIONS(7),
    [anon_sym_number] = ACTIONS(7),
    [anon_sym_string] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_func] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_bool] = ACTIONS(21),
    [anon_sym_number] = ACTIONS(21),
    [anon_sym_string] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(27), 1,
      anon_sym_EQ,
    ACTIONS(25), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(23), 11,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [28] = 3,
    ACTIONS(29), 1,
      anon_sym_EQ,
    ACTIONS(25), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(23), 11,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [56] = 12,
    ACTIONS(5), 1,
      anon_sym_func,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(6), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_program_repeat1,
    STATE(14), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [102] = 12,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_func,
    ACTIONS(41), 1,
      anon_sym_return,
    ACTIONS(44), 1,
      anon_sym_DASH,
    ACTIONS(47), 1,
      anon_sym_BANG,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(53), 2,
      sym_number,
      sym_string,
    ACTIONS(38), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(6), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_program_repeat1,
    STATE(14), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [148] = 3,
    ACTIONS(60), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
    ACTIONS(58), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
  [175] = 2,
    ACTIONS(21), 9,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_EQ,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(19), 11,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [200] = 3,
    ACTIONS(62), 1,
      anon_sym_EQ,
    ACTIONS(25), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(23), 11,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [227] = 3,
    ACTIONS(64), 1,
      anon_sym_EQ,
    ACTIONS(25), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(23), 11,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [254] = 6,
    ACTIONS(60), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(74), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(66), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(72), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(68), 7,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [287] = 4,
    ACTIONS(60), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(56), 7,
      ts_builtin_sym_end,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
    ACTIONS(58), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
  [316] = 2,
    ACTIONS(58), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(56), 11,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [341] = 6,
    ACTIONS(60), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(74), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(76), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(72), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(78), 7,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [374] = 6,
    ACTIONS(60), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(74), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(72), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(82), 7,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [407] = 2,
    ACTIONS(86), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(84), 11,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [432] = 2,
    ACTIONS(86), 9,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(84), 11,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [457] = 6,
    ACTIONS(60), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(74), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(72), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(90), 7,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [490] = 2,
    ACTIONS(86), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(84), 11,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [514] = 4,
    ACTIONS(92), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(56), 7,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
    ACTIONS(58), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
  [542] = 2,
    ACTIONS(86), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(84), 11,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [566] = 6,
    ACTIONS(92), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(80), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(96), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(82), 6,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [598] = 6,
    ACTIONS(92), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(102), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(96), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(100), 6,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [630] = 6,
    ACTIONS(92), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(88), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(96), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(90), 6,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [662] = 2,
    ACTIONS(58), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(56), 11,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [686] = 3,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(58), 8,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      sym_identifier,
    ACTIONS(56), 9,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
      sym_number,
      sym_string,
  [712] = 6,
    ACTIONS(92), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(66), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(96), 4,
      anon_sym_EQ_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(68), 6,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
  [744] = 11,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(109), 1,
      anon_sym_return,
    ACTIONS(112), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      anon_sym_BANG,
    ACTIONS(118), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(28), 1,
      aux_sym_block_repeat1,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(121), 2,
      sym_number,
      sym_string,
    ACTIONS(104), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(23), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [785] = 11,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(28), 1,
      aux_sym_block_repeat1,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(134), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(23), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [826] = 11,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(29), 1,
      aux_sym_block_repeat1,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(134), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(23), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [867] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(138), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(25), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [902] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(140), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(19), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [937] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(142), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(22), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [972] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(144), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(18), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1007] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(146), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(27), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1042] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(148), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(11), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1077] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(150), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(20), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1112] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(152), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(24), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1147] = 9,
    ACTIONS(126), 1,
      anon_sym_return,
    ACTIONS(128), 1,
      anon_sym_DASH,
    ACTIONS(130), 1,
      anon_sym_BANG,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(9), 1,
      sym_variable_declaration,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(154), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(26), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1182] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(156), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(12), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1217] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(158), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(16), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1252] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(160), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(13), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1287] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(162), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(15), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1322] = 9,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(4), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(164), 2,
      sym_number,
      sym_string,
    ACTIONS(7), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
    STATE(7), 5,
      sym_return_statement,
      sym__expression,
      sym_variable_definition,
      sym_unary_expression,
      sym_binary_expression,
  [1357] = 2,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(168), 6,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      sym_identifier,
  [1373] = 2,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(172), 6,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      sym_identifier,
  [1389] = 2,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(176), 6,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      sym_identifier,
  [1405] = 2,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(180), 6,
      anon_sym_func,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_return,
      sym_identifier,
  [1421] = 4,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_block,
    STATE(61), 2,
      sym__type,
      sym_primitive_type,
    ACTIONS(182), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
  [1437] = 4,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(182), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
  [1452] = 3,
    STATE(60), 1,
      sym_variable_declaration,
    STATE(65), 1,
      sym_primitive_type,
    ACTIONS(182), 3,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
  [1464] = 1,
    ACTIONS(188), 4,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_LBRACE,
  [1471] = 1,
    ACTIONS(190), 4,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_LBRACE,
  [1478] = 1,
    ACTIONS(192), 4,
      anon_sym_bool,
      anon_sym_number,
      anon_sym_string,
      anon_sym_LBRACE,
  [1485] = 3,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_parameter_list_repeat1,
  [1495] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_parameter_list_repeat1,
  [1505] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_parameter_list_repeat1,
  [1515] = 1,
    ACTIONS(205), 2,
      anon_sym_LBRACE,
      sym_identifier,
  [1520] = 2,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_parameter_list,
  [1527] = 1,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1532] = 2,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_block,
  [1539] = 1,
    ACTIONS(209), 1,
      sym_identifier,
  [1543] = 1,
    ACTIONS(211), 1,
      sym_identifier,
  [1547] = 1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [1551] = 1,
    ACTIONS(215), 1,
      sym_identifier,
  [1555] = 1,
    ACTIONS(217), 1,
      sym_identifier,
  [1559] = 1,
    ACTIONS(219), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 56,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 148,
  [SMALL_STATE(8)] = 175,
  [SMALL_STATE(9)] = 200,
  [SMALL_STATE(10)] = 227,
  [SMALL_STATE(11)] = 254,
  [SMALL_STATE(12)] = 287,
  [SMALL_STATE(13)] = 316,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 374,
  [SMALL_STATE(16)] = 407,
  [SMALL_STATE(17)] = 432,
  [SMALL_STATE(18)] = 457,
  [SMALL_STATE(19)] = 490,
  [SMALL_STATE(20)] = 514,
  [SMALL_STATE(21)] = 542,
  [SMALL_STATE(22)] = 566,
  [SMALL_STATE(23)] = 598,
  [SMALL_STATE(24)] = 630,
  [SMALL_STATE(25)] = 662,
  [SMALL_STATE(26)] = 686,
  [SMALL_STATE(27)] = 712,
  [SMALL_STATE(28)] = 744,
  [SMALL_STATE(29)] = 785,
  [SMALL_STATE(30)] = 826,
  [SMALL_STATE(31)] = 867,
  [SMALL_STATE(32)] = 902,
  [SMALL_STATE(33)] = 937,
  [SMALL_STATE(34)] = 972,
  [SMALL_STATE(35)] = 1007,
  [SMALL_STATE(36)] = 1042,
  [SMALL_STATE(37)] = 1077,
  [SMALL_STATE(38)] = 1112,
  [SMALL_STATE(39)] = 1147,
  [SMALL_STATE(40)] = 1182,
  [SMALL_STATE(41)] = 1217,
  [SMALL_STATE(42)] = 1252,
  [SMALL_STATE(43)] = 1287,
  [SMALL_STATE(44)] = 1322,
  [SMALL_STATE(45)] = 1357,
  [SMALL_STATE(46)] = 1373,
  [SMALL_STATE(47)] = 1389,
  [SMALL_STATE(48)] = 1405,
  [SMALL_STATE(49)] = 1421,
  [SMALL_STATE(50)] = 1437,
  [SMALL_STATE(51)] = 1452,
  [SMALL_STATE(52)] = 1464,
  [SMALL_STATE(53)] = 1471,
  [SMALL_STATE(54)] = 1478,
  [SMALL_STATE(55)] = 1485,
  [SMALL_STATE(56)] = 1495,
  [SMALL_STATE(57)] = 1505,
  [SMALL_STATE(58)] = 1515,
  [SMALL_STATE(59)] = 1520,
  [SMALL_STATE(60)] = 1527,
  [SMALL_STATE(61)] = 1532,
  [SMALL_STATE(62)] = 1539,
  [SMALL_STATE(63)] = 1543,
  [SMALL_STATE(64)] = 1547,
  [SMALL_STATE(65)] = 1551,
  [SMALL_STATE(66)] = 1555,
  [SMALL_STATE(67)] = 1559,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 2, .production_id = 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 2, .production_id = 2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(63),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(58),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(43),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(41),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(62),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(14),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3, .production_id = 5),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 3, .production_id = 5),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3, .production_id = 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 3, .production_id = 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(58),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(33),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(32),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(66),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(10),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(23),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 6),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, .production_id = 6),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, .production_id = 7),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, .production_id = 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(51),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_BORING_PROGRAMMING_LANGAGE(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
